In [77]:
import pandas as pd

In [ ]:
dset=pd.read_csv("diabetes.csv")

In [78]:
dset

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1
...,...,...,...,...,...,...,...,...,...
763,10,101,76,48,180,32.9,0.171,63,0
764,2,122,70,27,0,36.8,0.340,27,0
765,5,121,72,23,112,26.2,0.245,30,0
766,1,126,60,0,0,30.1,0.349,47,1
767,1,93,70,31,0,30.4,0.315,23,0

In [ ]:
from sklearn.preprocessing import StandardScaler

kl=StandardScaler()

kl.fit(dset.drop("Outcome",axis=1))

stsc=kl.transform(dset.drop("Outcome",axis=1))

new_df=pd.DataFrame(stsc,columns=dset.columns[:-1])

In [79]:
new_df

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
0,0.639947,0.848324,0.149641,0.907270,-0.692891,0.204013,0.468492,1.425995
1,-0.844885,-1.123396,-0.160546,0.530902,-0.692891,-0.684422,-0.365061,-0.190672
2,1.233880,1.943724,-0.263941,-1.288212,-0.692891,-1.103255,0.604397,-0.105584
3,-0.844885,-0.998208,-0.160546,0.154533,0.123302,-0.494043,-0.920763,-1.041549
4,-1.141852,0.504055,-1.504687,0.907270,0.765836,1.409746,5.484909,-0.020496
...,...,...,...,...,...,...,...,...
763,1.827813,-0.622642,0.356432,1.722735,0.870031,0.115169,-0.908682,2.532136
764,-0.547919,0.034598,0.046245,0.405445,-0.692891,0.610154,-0.398282,-0.531023
765,0.342981,0.003301,0.149641,0.154533,0.279594,-0.735190,-0.685193,-0.275760
766,-0.844885,0.159787,-0.470732,-1.288212,-0.692891,-0.240205,-0.371101,1.170732
767,-0.844885,-0.873019,0.046245,0.656358,-0.692891,-0.202129,-0.473785,-0.871374

In [81]:
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test=train_test_split(new_df,dset["Outcome"],test_size=0.3,random_state=42)

In [80]:
x_train

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
334,-0.844885,-0.810425,-0.470732,-0.159107,-0.189283,-1.027104,-0.639892,-0.956462
139,0.342981,-0.497453,0.149641,0.530902,2.129051,0.622846,-0.944924,-0.445935
485,-1.141852,0.441461,-0.057150,1.346366,1.477833,1.308210,-0.322779,-0.786286
547,0.046014,0.316272,-0.057150,0.029077,0.748470,0.140553,-0.941903,-0.445935
18,-0.844885,-0.560048,-2.021665,1.095454,0.027790,1.435129,-0.872441,-0.020496
...,...,...,...,...,...,...,...,...
71,0.342981,0.566649,-0.263941,0.907270,0.522715,-0.430583,-0.183854,-0.616111
106,-0.844885,-0.779128,2.734528,-1.288212,-0.692891,-1.217483,-0.799958,-0.531023
270,1.827813,-0.622642,0.873409,1.032726,-0.692891,1.727044,2.005732,0.404942
435,-1.141852,0.629244,-3.572597,-1.288212,-0.692891,1.320902,-0.805998,-0.360847
102,-1.141852,0.128489,1.390387,-1.288212,-0.692891,-1.204791,-0.633851,-1.041549

In [82]:
y_train

334    0
139    0
485    1
547    0
18     0
      ..
71     0
106    0
270    1
435    1
102    0
Name: Outcome, Length: 537, dtype: int64

In [83]:
from sklearn.neural_network import MLPClassifier
zh=MLPClassifier(random_state=1)

In [91]:
zh = MLPClassifier()
zh.fit(x_train,y_train)

klm=zh.predict(x_test)

/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:696: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  ConvergenceWarning,

In [92]:
from sklearn.metrics import confusion_matrix,classification_report

In [93]:
print(confusion_matrix(klm,y_test))
print(classification_report(klm,y_test))

[[121  29]
 [ 30  51]]
              precision    recall  f1-score   support

           0       0.80      0.81      0.80       150
           1       0.64      0.63      0.63        81

    accuracy                           0.74       231
   macro avg       0.72      0.72      0.72       231
weighted avg       0.74      0.74      0.74       231